### ISSUE TITLE
Location of banlist

### ISSUE THREAD

**Issue by notmayo** [yuzu-emu/yuzu-multiplayer-dedicated#1]
Good afternoon,

I have managed to get a few containers spun up, however, I would like to figure out what shell, or where I can mount a banlist to. I'm using docker compose, but generic information will help. I cannot docker exec -it the container to get into a shell like I can with other containers to find out this info myself.

**Comment by liushuyu** [comment]
> Good afternoon,

Hi there,

> I would like to figure out what shell, or where I can mount a banlist to. I'm using docker compose, but generic information will help.

I think you are looking in the wrong direction. Usually, you would mount the ban list from the host machine to persist its data across container restarts. To do this, try:

```bash
docker run -v /root/banlist.txt:/mnt/banlist.txt \
--publish <your_port_number>:<your_port_number>/udp -d yuzuemu/yuzu-multiplayer-dedicated \
--ban-list-file /mnt/banlist.txt <... your other arguments>
```

> I cannot docker exec -it the container to get into a shell like I can with other containers to find out this info myself.

This is to be expected. Our image is security hardened, so all the unnecessary files for the `yuzu-room` function are removed. This includes any shell and other utilities (including `ls`, `pwd`, etc.) However, you don't need a shell in the container to do this, see my instructions to your previous question.

I hope this helps. By doing this, you can also share the ban list across different containers, it's unsafe but somewhat usable.

**Comment by liushuyu** [comment]
Does that help with your question? If so, I will mark this issue as completed.

**Comment by notmayo** [comment]
Yep! You have helped greatly, thank you!
